# Generated by Django 6.0.2 on 2026-03-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('cert_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('issue_date', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
    ]
