# Generated by Django 5.2.10 on 2026-03-23 18:35

from django.db import migrations


def add_certificates(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    certificates_data = [
        {
            'cert_id': 'INFOD-SOC-2025-001',
            'student_name': 'Rakesh Jimmidi',
            'course_name': 'SOC Analyst - Level 1',
            'issue_date': '5th October 2025',
        },
        {
            'cert_id': 'INFOD-SOC-2025-002',
            'student_name': 'Dasari Tejesh',
            'course_name': 'SOC Analyst - Level 1',
            'issue_date': '5th October 2025',
        },
        {
            'cert_id': 'INFOD-SOC-2025-003',
            'student_name': 'Kosuri Mamatha valli',
            'course_name': 'SOC Analyst - Level 1',
            'issue_date': '5th October 2025',
        },
        {
            'cert_id': 'INFOD-SOC-2025-004',
            'student_name': 'Yedla Tejomaya',
            'course_name': 'SOC Analyst - Level 1',
            'issue_date': '5th October 2025',
        },
    ]
    
    for cert_data in certificates_data:
        Certificate.objects.get_or_create(
            cert_id=cert_data['cert_id'],
            defaults=cert_data
        )


def remove_certificates(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    Certificate.objects.filter(cert_id__in=[
        'INFOD-SOC-2025-001',
        'INFOD-SOC-2025-002',
        'INFOD-SOC-2025-003',
        'INFOD-SOC-2025-004',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_certificates, remove_certificates),
    ]
