# Generated by Django 6.0.2 on 2026-05-04 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.CharField(db_index=True, max_length=200)),
                ('quiz_id', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('passed', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course_slug'], name='courses_qui_user_id_13b232_idx')],
                'unique_together': {('user', 'course_slug', 'quiz_id')},
            },
        ),
    ]
