# Generated by Django 5.2.10 on 2026-03-12 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('code', 'course_slug', 'user')},
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.promocode'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['promo_code', 'used_at'], name='payments_pr_promo_c_e6d6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['code', 'course_slug', 'used_at'], name='payments_pr_code_2aff3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(fields=('code', 'course_slug'), name='uniq_promo_code_per_course'),
        ),
    ]
