# Generated by Django 6.0.2 on 2026-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_promocodeusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('course_slug', models.SlugField()),
                ('max_uses', models.PositiveIntegerField(default=10, help_text='Maximum number of times this code can be used')),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='promocodeusage',
            name='payments_pr_code_adaf1a_idx',
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code', 'course_slug', 'is_active'], name='payments_pr_code_4abf8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together={('code', 'course_slug')},
        ),
        migrations.DeleteModel(
            name='PromoCodeUsage',
        ),
    ]
