# Generated by Django 6.0.2 on 2026-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_promocodeusage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(default=100, help_text='Discount percentage (0-100). 100 = free, 50 = 50% off'),
        ),
    ]
