# Generated by Django 6.0.2 on 2026-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_promocode_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO alpha-2 (US, GB, PK…)', max_length=2, unique=True)),
                ('currency_code', models.CharField(help_text='USD, GBP, PKR…', max_length=3)),
                ('currency_symbol', models.CharField(help_text='$, £, ₨…', max_length=10)),
                ('price_easy', models.DecimalField(blank=True, decimal_places=2, help_text='Override for easy courses (₹499 base). Leave blank for auto-convert.', max_digits=10, null=True)),
                ('price_medium', models.DecimalField(blank=True, decimal_places=2, help_text='Override for medium courses (₹799 base). Leave blank for auto-convert.', max_digits=10, null=True)),
                ('price_hard', models.DecimalField(blank=True, decimal_places=2, help_text='Override for hard courses (₹1199 base). Leave blank for auto-convert.', max_digits=10, null=True)),
                ('price_bundle', models.DecimalField(blank=True, decimal_places=2, help_text='Override for all-courses bundle (₹3999 base). Leave blank for auto-convert.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country Pricing',
                'verbose_name_plural': 'Country Pricing',
                'ordering': ['country_code'],
            },
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='amount_charged',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount charged in the payment currency (e.g. 9.99 USD)', max_digits=10, null=True),
        ),
    ]
