# Generated by Django 6.0.2 on 2026-03-10 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_promocode_alter_promocodeusage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('course_slug', models.SlugField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='promocode',
            name='payments_pr_code_4abf8e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, help_text='Maximum unique users allowed (0 = unlimited)'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code', 'course_slug'], name='payments_pr_code_f894f0_idx'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['code', 'used_at'], name='payments_pr_code_adaf1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('code', 'user')},
        ),
    ]
