"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

import dj_database_url
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default="django-insecure-change-me-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# Allow local development hosts
_railway_hosts = [
    config("RAILWAY_STATIC_URL", default="").strip(),
    config("RAILWAY_PUBLIC_DOMAIN", default="").strip(),
]

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".railway.app",
    ".up.railway.app",
    "api.infosecdairies.io",
    "infosecdairies.io",
    *[h for h in _railway_hosts if h],
]


from datetime import timedelta

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "courses",
    "accounts",
    "certificates",
    "payments",
    "leads",

    # Authentication helpers
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.linkedin_oauth2",
    "dj_rest_auth",
    "dj_rest_auth.registration",
]

SITE_ID = 2  # Use the Site with domain 127.0.0.1:8000

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS / CSRF settings for local development
# Frontend runs on http://127.0.0.1:8081 (and sometimes http://localhost:8081)
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)
CORS_ALLOW_CREDENTIALS = True

_csrf_trusted_origins = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:8081,http://127.0.0.1:8081",
    cast=lambda v: [s.strip() for s in v.split(",")]
)

CORS_ALLOWED_ORIGINS = [
    *_csrf_trusted_origins,
    "https://infosecdairies.io",
    "https://www.infosecdairies.io",
    "https://api.infosecdairies.io",
]

CSRF_TRUSTED_ORIGINS = [
    *_csrf_trusted_origins,
    "https://*.railway.app",
    "https://*.up.railway.app",
    "https://api.infosecdairies.io",
    "https://infosecdairies.io",
    "https://www.infosecdairies.io",
]

_railway_public_domain = config("RAILWAY_PUBLIC_DOMAIN", default="").strip()
if _railway_public_domain:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_railway_public_domain}")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# django-allauth: configure for email-only User (no username field)
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# allauth: go straight to the provider on GET /accounts/google/login/
SOCIALACCOUNT_LOGIN_ON_GET = True

# Where to send users after allauth login.
# Point this at a frontend callback that will exchange the
# session-based login for JWT tokens and then redirect into
# the app dashboard.
_frontend_url = config("FRONTEND_URL", default="http://127.0.0.1:8081").rstrip("/")
LOGIN_REDIRECT_URL = f"{_frontend_url}/auth/google-callback"

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
}

SIMPLE_JWT = {
    # How long a user stays logged in before the access token expires.
    # Increase this so the app does not "log out" after ~10-15 minutes.
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
}

# dj-rest-auth configuration: we're using SimpleJWT tokens, not DRF Token model
DJ_REST_AUTH = {
    "TOKEN_MODEL": None,
}

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (uploaded certificates)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# In development, send emails (including OTP codes) to the console so
# you can see them in the runserver output. For production, replace this
# with a real SMTP backend.
EMAIL_BACKEND = config(
    "DJANGO_EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="infosecdairies@gmail.com")

EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)

RESEND_API_KEY = config("RESEND_API_KEY", default="")
RESEND_TIMEOUT = config("RESEND_TIMEOUT", default=EMAIL_TIMEOUT, cast=int)

# Safety fallback: if SMTP creds are present, always use SMTP backend.
# This prevents accidentally using the console backend in production.
if RESEND_API_KEY:
    EMAIL_BACKEND = "backend.email_backends.ResendEmailBackend"
elif EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

print(
    "[email-config] EMAIL_BACKEND=", EMAIL_BACKEND,
    "DEFAULT_FROM_EMAIL=", DEFAULT_FROM_EMAIL,
    "EMAIL_HOST=", EMAIL_HOST,
    "EMAIL_PORT=", EMAIL_PORT,
    "EMAIL_USE_TLS=", EMAIL_USE_TLS,
    "EMAIL_HOST_USER=", EMAIL_HOST_USER,
    "EMAIL_HOST_PASSWORD_SET=", bool(EMAIL_HOST_PASSWORD),
    flush=True,
)

# Razorpay (set via environment variables)
RAZORPAY_KEY_ID = config("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = config("RAZORPAY_KEY_SECRET", "")

# Payments: when enabled, paid courses charge ₹1 for testing
PAYMENTS_TEST_MODE = config("PAYMENTS_TEST_MODE", default=False, cast=bool)
